# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.0
_src_path: gh:nf-core/modules-template
ci: github
copyright_date: "2026"
copyright_holder: Giang Nguyen
copyright_license: MIT License
default_branch: main
description: An nf-core modules repository hosting Nextflow DSL2 modules for the gianglabs
  organization.
repo_host: https://github.com
repo_name: nf-modules
repo_org_name: gianglabs
short_org_name: gianglabs
